apiVersion: batch/v1
kind: Job
metadata:
  name: demo-train-bert
  namespace: demo
  labels:
    app.kubernetes.io/name: radix-demo
    app.kubernetes.io/component: training
    app.kubernetes.io/job-type: train-bert
  annotations:
    app.kubernetes.io/job-type: "train-bert"
    gpu.mem.gi: "40"
    ml.batch_size: "16"
    scheduler.radix.ai/tenant: "research"
    scheduler.radix.ai/priority: "high"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radix-demo
        app.kubernetes.io/component: training
        app.kubernetes.io/job-type: train-bert
      annotations:
        app.kubernetes.io/job-type: "train-bert"
        gpu.mem.gi: "40"
        ml.batch_size: "16"
        scheduler.radix.ai/tenant: "research"
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
        args:
        - |
          echo "Starting BERT training simulation..."
          echo "Job Type: train-bert"
          echo "GPU Memory Required: 40GB"
          echo "Batch Size: 16"
          echo "Tenant: research"
          echo "Simulating training for 30 seconds..."
          sleep 30
          echo "Training completed successfully!"
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: "1"
        env:
        - name: JOB_TYPE
          value: "train-bert"
        - name: GPU_MEMORY_GB
          value: "40"
        - name: BATCH_SIZE
          value: "16"
